"""add usage_records table

Revision ID: fcb94995788e
Revises: c757e9a2e7d7
Create Date: 2026-02-19 21:30:50.105939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcb94995788e'
down_revision: Union[str, Sequence[str], None] = 'c757e9a2e7d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('requests', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'model', 'usage_date', 'user_id', name='uq_usage_record')
    )
    op.create_index(op.f('ix_usage_records_id'), 'usage_records', ['id'], unique=False)
    op.create_index(op.f('ix_usage_records_model'), 'usage_records', ['model'], unique=False)
    op.create_index(op.f('ix_usage_records_provider'), 'usage_records', ['provider'], unique=False)
    op.create_index(op.f('ix_usage_records_usage_date'), 'usage_records', ['usage_date'], unique=False)
    op.create_index(op.f('ix_usage_records_user_id'), 'usage_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_records_user_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_usage_date'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_provider'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_model'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_id'), table_name='usage_records')
    op.drop_table('usage_records')
    # ### end Alembic commands ###
